theme: jekyll-theme-hacker

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: juanrgar
description: Juan García Blanco's Personal Page
show_downloads: false
show_repository_link: false
google_analytics: G-27R8CZWR9B
